image: alpine:latest # slimmer than docker:latest

variables:
  ROLLOUT_RESOURCE_TYPE: deployment

stages:
  - build
  - test
  - review
  - staging
  - canary
  - production
  - dast
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - cleanup


include:  
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml
  - template: Jobs/DAST-Default-Branch-Deploy.gitlab-ci.yml
  - template: Security/DAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


unit:
  image: python:3.6
  stage: test
  script:
    - apt update -y
    - apt install libmariadb3 libmariadb-dev sqlite3 libsqlite3-dev -y
    - pip install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install unittest-xml-reporting
    - python -m xmlrunner tests/test_db.py
    - mv TEST* unit.xml
  artifacts:
    when: always
    paths:
      - unit.xml
    reports:
      junit: unit.xml

gemnasium-python-dependency_scanning:
  before_script:
    - apt update
    - apt install libmariadb3 libmariadb-dev sqlite3 libsqlite3-dev -y
